# Generated by Django 5.0.6 on 2024-06-29 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('completed', models.IntegerField()),
                ('not_completed', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
