name: CI for React and Django

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: your_db_name
          POSTGRES_USER: your_user
          POSTGRES_PASSWORD: your_password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2

    # Set up Python for Django
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    # Upgrade pip
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    # Install Django dependencies
    - name: Install Django dependencies
      run: |
        pip install -r requirements.txt

    # Set up Node for React
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    # Install React dependencies
    - name: Install React dependencies
      run: |
        cd frontend
        npm install

    # Build React project
    - name: Build React app
      run: |
        cd frontend
        npm run build

    # Run Django migrations and tests
    - name: Run Django tests
      run: |
        python manage.py migrate
        python manage.py test

    # Run React tests
    - name: Run React tests
      run: |
        cd frontend
        npm test

    # Optional: Linting step for React
    - name: Lint React code
      run: |
        cd frontend
        npm run lint

    # Optional: Linting step for Django
    - name: Lint Django code
      run: |
        cd myapp
        flake8
