name: CI/CD for Local Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Adjust the version as needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
#haven't really done the cp yet
    - name: Notify deployment
      run: |
        echo "Deployment to local server is ready. Follow the instructions below to deploy manually."
        echo ""
        echo "1. Pull the latest changes on your local machine:"
        echo "   git pull origin main"
        echo ""
        echo "2. Activate your virtual environment:"
        echo "   source /path/to/your/virtualenv/bin/activate"
        echo ""
        echo "3. Install dependencies:"
        echo "   pip install -r requirements.txt"
        echo ""
        echo "4. Run database migrations:"
        echo "   python manage.py migrate"
        echo ""
        echo "5. Restart the Django service (if running with systemd):"
        echo "   sudo systemctl restart your_django_service"
